import React, { useState, useEffect } from 'react';
import { Image, Modal, Button, Form } from 'react-bootstrap';
import { motion } from 'framer-motion';
import AdminNavbar from '../../../commponents/adminNavbar';
import backgroundImage from '../../../assets/backgroundAdmin.jpeg';
import axios from 'axios';
import Swal from 'sweetalert2';

const RegisterTechnician = () => {
  const [formData, setFormData] = useState({
    surname: '',
    initials: '',
    email: '',
    contact: '',
    password: '',
    currentEmail: "",
    newEmail: "",
    currentPassword: "",
    newPassword: "",
    confirmPassword: "",
  });

  const [currentTime, setCurrentTime] = useState(new Date().toLocaleTimeString());
  const [showProfileModal, setShowProfileModal] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [currentPwd, setCurrentPwd] = useState('');
  const [newPwd, setNewPwd] = useState('');
  const [confirmPwd, setConfirmPwd] = useState('');
  const [settingsMode, setSettingsMode] = useState("");
  
   const [adminInfo, setAdminInfo] = useState({
      surname: "",
      initials: "",
      email: "",
      contact: "",
    });

 
  const adminEmail = 'admin@example.com';
  const adminRole = 'Admin';
  const adminInitials = 'J';
  const adminContact = '123-456-7890';
  const adminSurname = 'Doe';
  useEffect(() => {
    setAdminInfo({
      email: adminEmail,
      role: adminRole,
      initials: adminInitials,
      contact: adminContact,
      surname: adminSurname
    });
  }, []);
  const glassCardStyle = {
    background: "rgba(255, 255, 255, 0.1)",
    borderRadius: "15px",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    boxShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
  };

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentTime(new Date().toLocaleTimeString());
    }, 1000);
    return () => clearInterval(timer);
  }, []);
  const handleEmailChange = () => {
  const { currentPassword, newEmail } = formData;

  if (!currentPassword || !newEmail) {
    alert("Please fill in both fields.");
    return;
  }

  console.log("Changing email:", { currentPassword, newEmail });
  alert("Email updated successfully.");
  resetModal();
};

const handlePasswordChange = () => {
  const { currentPassword, newPassword, confirmPassword } = formData;

  if (!currentPassword || !newPassword || !confirmPassword) {
    alert("Please fill in all fields.");
    return;
  }

  if (newPassword !== confirmPassword) {
    alert("Passwords do not match.");
    return;
  }

  console.log("Changing password:", { currentPassword, newPassword });
  alert("Password updated successfully.");
  resetModal();
};

const resetModal = () => {
  setFormData({
    currentPassword: "",
    newEmail: "",
    newPassword: "",
    confirmPassword: "",
  });
  setSettingsMode("");
};


  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    const payload = {
      ...formData,
      role: 'technician' // Role is autogenerated here
    };
    
    const API_URL = process.env.REACT_APP_API_URL;

    try {
      const res = await axios.post(`${API_URL}addTechnician`, payload);
      Swal.fire({
        icon: 'success',
        title: 'Technician Registered',
        text: 'The technician has been successfully added!',
      });

      setFormData({
        surname: '',
        initials: '',
        email: '',
        contact: '',
        password: ''
      });
    } catch (err) {
      Swal.fire({
        icon: 'error',
        title: 'Registration Failed',
        text: err.response?.data?.message || 'Something went wrong. Please try again.',
      });
    }
  };

  

  const backgroundStyle = {
    backgroundImage: `url(${backgroundImage})`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    minHeight: '100vh',
    color: 'white',
  };

  return (
    <div className="d-flex">
      <AdminNavbar />
      <motion.div
        initial={{ opacity: 0, y: 50 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="flex-grow-1 p-4"
        style={backgroundStyle}
      >
        <div className="d-flex justify-content-between align-items-center mb-4">
          <h2 className="mb-0 text-white text-uppercase" style={{
            fontWeight: 'bold',
            textShadow: '2px 2px 4px rgba(0, 0, 0, 0.6)',
            backgroundColor: 'rgba(0, 0, 0, 0.3)',
            padding: '6px 12px',
            borderRadius: '8px',
          }}>
            Add Technician
          </h2>
          <div className="d-flex align-items-center gap-3">
            <span className="text-white">{currentTime}</span>
            <Image
              src="https://cdn-icons-png.flaticon.com/512/149/149071.png"
              roundedCircle
              alt="Profile"
              width={32}
              height={32}
              style={{ cursor: 'pointer' }}
              onClick={() => setShowProfileModal(true)}
            />
          </div>
        </div>

        <div className="d-flex justify-content-center align-items-center" style={{ minHeight: '80vh' }}>
          <motion.div
            className="container"
            style={{ maxWidth: '700px' }}
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ delay: 0.2, duration: 0.6 }}
          >
            <div
              className="card shadow-sm border-0 rounded-4"
              style={{
                background: 'rgba(255, 255, 255, 0.1)',
                backdropFilter: 'blur(8px)',
                WebkitBackdropFilter: 'blur(8px)',
                color: 'white',
              }}
            >
              <div className="card-body p-4">
                <h3 className="card-title text-center mb-4">🛠️ Register Technician</h3>
                <form onSubmit={handleSubmit} className="row g-3">
                  {[
                    { label: 'Surname', name: 'surname' },
                    { label: 'Initials', name: 'initials' },
                    { label: 'Email', name: 'email', type: 'email' },
                    { label: 'Contact', name: 'contact' },
                    { label: 'Password', name: 'password', type: 'password' },
                  ].map(({ label, name, type = 'text' }, idx) => (
                    <div className="col-md-6" key={idx}>
                      <label className="form-label">{label}</label>
                      <input
                        type={type}
                        name={name}
                        value={formData[name]}
                        onChange={handleChange}
                        className="form-control"
                        required
                      />
                    </div>
                  ))}

                  <div className="col-12 mt-3">
                    <button type="submit" className="btn btn-primary w-100">Register Technician</button>
                  </div>
                </form>
              </div>
            </div>
            <p className="text-muted text-center mt-3">Only technician roles are currently supported.</p>
          </motion.div>
        </div>
      </motion.div>

      {showProfileModal && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="position-fixed top-0 start-0 w-100 h-100 d-flex justify-content-center align-items-center"
                  style={{
                    backdropFilter: "blur(8px)",
                    backgroundColor: "rgba(0, 0, 0, 0.4)",
                    zIndex: 1050,
                  }}
                  onClick={() => {
                    setShowProfileModal(false);
                    setSettingsMode("");
                    setFormData({
                      currentPassword: "",
                      newEmail: "",
                      newPassword: "",
                      confirmPassword: "",
                    });
                  }}
                >
                  <motion.div
                    initial={{ scale: 0.8, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    className="p-4"
                    style={{
                      width: "380px",
                      color: "#fff",
                      borderRadius: "20px",
                      background: "rgba(255, 255, 255, 0.15)",
                      boxShadow: "0 8px 32px 0 rgba(31, 38, 135, 0.37)",
                    }}
                    onClick={(e) => e.stopPropagation()}
                  >
                    <div className="text-center mb-3">
                      <img
                        src="https://cdn-icons-png.flaticon.com/512/149/149071.png"
                        alt="Profile"
                        className="rounded-circle"
                        style={{ width: "80px", height: "80px" }}
                      />
                      <h5 className="mt-3">Admin Profile</h5>
                      <p>
                        <strong>Initials:</strong> {adminInfo.initials}
                      </p>
                      <p>
                        <strong>Surname:</strong> {adminInfo.surname}
                      </p>
                      <p>
                        <strong>Email:</strong> {adminInfo.email}
                      </p>
                      <p>
                        <strong>Contact:</strong> {adminInfo.contact}
                      </p>
                    </div>
      
                    <hr className="text-white" />
      
                    {settingsMode === "" && (
                      <div className="d-grid gap-2">
                        <button
                          className="btn btn-outline-light"
                          onClick={() => setSettingsMode("options")}
                        >
                          Profile Settings
                        </button>
                        <button className="btn btn-outline-danger">Logout</button>
                        <button
                          className="btn btn-outline-secondary"
                          onClick={() => setShowProfileModal(false)}
                        >
                          Close
                        </button>
                      </div>
                    )}
      
                    {settingsMode === "options" && (
                      <div className="d-grid gap-2">
                        <button
                          className="btn btn-outline-warning"
                          onClick={() => setSettingsMode("email")}
                        >
                          Change Email
                        </button>
                        <button
                          className="btn btn-outline-info"
                          onClick={() => setSettingsMode("password")}
                        >
                          Change Password
                        </button>
                        <button
                          className="btn btn-outline-secondary"
                          onClick={() => setSettingsMode("")}
                        >
                          Back
                        </button>
                      </div>
                    )}
      
                    {settingsMode === "email" && (
                      <>
                        <h6 className="text-center mb-3">Change Email</h6>
                        <label className="form-label text-white">
                          Current Password
                        </label>
                        <input
                          type="password"
                          className="form-control mb-2"
                          value={formData.currentPassword}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              currentPassword: e.target.value,
                            })
                          }
                          placeholder="Enter current password"
                        />
                        <label className="form-label text-white">New Email</label>
                        <input
                          type="email"
                          className="form-control mb-3"
                          value={formData.newEmail}
                          onChange={(e) =>
                            setFormData({ ...formData, newEmail: e.target.value })
                          }
                          placeholder="Enter new email"
                        />
                        <div className="d-grid gap-2">
                          <button
                            className="btn btn-success"
                            onClick={handleEmailChange}
                          >
                            Save Email
                          </button>
                          <button
                            className="btn btn-outline-light"
                            onClick={() => setSettingsMode("options")}
                          >
                            Back
                          </button>
                        </div>
                      </>
                    )}
      
                    {settingsMode === "password" && (
                      <>
                        <h6 className="text-center mb-3">Change Password</h6>
                        <label className="form-label text-white">
                          Current Password
                        </label>
                        <input
                          type="password"
                          className="form-control mb-2"
                          value={formData.currentPassword}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              currentPassword: e.target.value,
                            })
                          }
                          placeholder="Enter current password"
                        />
                        <label className="form-label text-white">New Password</label>
                        <input
                          type="password"
                          className="form-control mb-2"
                          value={formData.newPassword}
                          onChange={(e) =>
                            setFormData({ ...formData, newPassword: e.target.value })
                          }
                          placeholder="Enter new password"
                        />
                        <label className="form-label text-white">
                          Confirm Password
                        </label>
                        <input
                          type="password"
                          className="form-control mb-3"
                          value={formData.confirmPassword}
                          onChange={(e) =>
                            setFormData({
                              ...formData,
                              confirmPassword: e.target.value,
                            })
                          }
                          placeholder="Confirm new password"
                        />
                        <div className="d-grid gap-2">
                          <button
                            className="btn btn-success"
                            onClick={handlePasswordChange}
                          >
                            Save Password
                          </button>
                          <button
                            className="btn btn-outline-light"
                            onClick={() => setSettingsMode("options")}
                          >
                            Back
                          </button>
                        </div>
                      </>
                    )}
                  </motion.div>
                </motion.div>
              )}
    </div>
  );
};

export default RegisterTechnician;
